'use client';
import {useEffect,useState} from 'react';
import {browserClient} from '@/lib/supabase/client';
export default function SignIn(){
 const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[create,setCreate]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const [providers,setProviders]=useState({google:false,apple:false});
 useEffect(()=>{const controller=new AbortController();fetch(process.env.NEXT_PUBLIC_SUPABASE_URL+'/auth/v1/settings',{headers:{apikey:process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY!},signal:controller.signal}).then(r=>r.ok?r.json():null).then(d=>{if(d?.external)setProviders({google:d.external.google===true,apple:d.external.apple===true})}).catch(()=>{});if(new URLSearchParams(window.location.search).has('error'))setMessage('The sign-in link could not be verified. Please try again.');return()=>controller.abort()},[]);
 const callback=()=>window.location.origin+'/auth/callback';
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setMessage('');try{
  const db=browserClient();
  if(create){const {data,error}=await db.auth.signUp({email,password,options:{emailRedirectTo:callback()}});if(error)throw error;if(data.session)window.location.assign('/#moves');else setMessage('Check your email to confirm your account, then return to ENOUGH.');}
  else{const {error}=await db.auth.signInWithPassword({email,password});if(error)throw error;window.location.assign('/#moves');}
 }catch{setMessage(create?'Your account could not be created. Check your details and try again.':'Sign-in failed. Check your email and password.');}finally{setBusy(false)}}
 async function social(provider:'google'|'apple'){setBusy(true);setMessage('');try{const {error}=await browserClient().auth.signInWithOAuth({provider,options:{redirectTo:callback()}});if(error)throw error;}catch{setMessage('This sign-in option is not connected yet. You can use email when available.');setBusy(false)}}
 return <main id="main" className="auth-page"><a href="/">ENOUGH.</a><h1>{create?'Keep your ENOUGH':'Welcome back'}</h1><p>Your profile, plans and moments, together.</p><form onSubmit={submit}><label className="field">Email<input type="email" autoComplete="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label className="field">Password<input type="password" autoComplete={create?'new-password':'current-password'} minLength={8} required value={password} onChange={e=>setPassword(e.target.value)}/></label><button className="primary" disabled={busy}>{create?'Create account':'Sign in'}</button></form><button className="text-button" disabled={busy} onClick={()=>{setCreate(!create);setMessage('')}}>{create?'I already have an account':'Create an account'}</button><a className="text-button" href="/recover">Forgot password?</a><div className="signin-options"><button className="secondary" disabled={busy||!providers.google} onClick={()=>social('google')}>Continue with Google</button><button className="secondary" disabled={busy||!providers.apple} onClick={()=>social('apple')}>Continue with Apple</button></div>{(!providers.google||!providers.apple)&&<p className="sample-note">Some sign-in options are not available yet.</p>}{message&&<p role="status">{message}</p>}<p><a href="/#moves">Keep browsing</a></p></main>;
}
