import test from 'node:test';
import assert from 'node:assert/strict';
import {emptyState,completeProfile,accept,finish,receipt,restore} from '../lib/journey.ts';
function configured(){const s=emptyState();Object.assign(s.profile,{preferences:['Outside'],interests:['Family time'],needs:['Nothing to add'],strengths:['I enjoy company'],activity:'Mostly seated',rhythms:['Calls'],window:'It varies',complete:true});return s;}
test('all four PINS categories and routines are required',()=>{const s=configured();assert.equal(completeProfile(s.profile),true);for(const key of ['preferences','interests','needs','strengths','rhythms'])assert.equal(completeProfile({...s.profile,[key]:[]}),false);assert.equal(completeProfile({...s.profile,activity:''}),false);assert.equal(completeProfile({...s.profile,window:''}),false);});
test('guest acceptance changes nothing; explicit demo acceptance records intent once',()=>{const s=configured();assert.deepEqual(accept(s,0),s);s.demo=true;const once=accept(s,0);assert.equal(once.entries.length,1);assert.equal(accept(once,0).entries.length,1);assert.equal(receipt(once.entries,'Today','AUD').rows.length,0);});
test('confirmed outcomes persist and cannot be counted twice',()=>{let s=configured();s.demo=true;s=accept(s,0);const id=s.entries[0].id;const result={minutes:18,outside:true,connecting:false,worthwhile:true,moneyCents:699};s=finish(s,id,result);s=finish(s,id,{...result,moneyCents:999});s=restore(JSON.stringify(s));const r=receipt(s.entries,'Today','AUD');assert.equal(r.money,699);assert.equal(r.outside,18);assert.equal(r.rows.length,1);assert.equal(r.connecting,0);});
test('receipt uses local periods and keeps currencies separate',()=>{const now=new Date(2026,9,7,12);const entries=[['AUD',699,new Date(2026,9,5,12)],['USD',800,new Date(2026,9,7,11)],['AUD',999,new Date(2026,9,4,12)]].map(([currency,moneyCents,date],i)=>({id:String(i),ideaId:0,status:'completed',acceptedAt:date.toISOString(),completedAt:date.toISOString(),minutes:10,outside:true,connecting:true,worthwhile:true,currency,moneyCents}));assert.equal(receipt(entries,'This week','AUD',now).money,699);assert.equal(receipt(entries,'Today','AUD',now).money,0);assert.equal(receipt(entries,'This week','AUD',now).outside,20);});
test('invalid outcomes and corrupt saved data fail intentionally',()=>{let s=configured();s.demo=true;s=accept(s,0);assert.throws(()=>finish(s,s.entries[0].id,{minutes:-1,moneyCents:0}));assert.throws(()=>restore('{'));assert.throws(()=>restore(JSON.stringify({...s,saved:[99]})));});
test('visual answers cannot change completion or receipt',()=>{const s=configured();const other={...s.profile,visual:['Country settings']};assert.equal(completeProfile(s.profile),completeProfile(other));assert.deepEqual(receipt(s.entries,'Today','AUD'),receipt(s.entries,'Today',other.currency));});
