import test from 'node:test';
import assert from 'node:assert/strict';
import {regions,regionChange,formatMoney,parseMoney,savingFromCost} from '../lib/regions.ts';
import {resumeSetup,setupInstruction} from '../lib/onboarding.ts';
import {emptyState,completeProfile,accept,finish,receipt,restore} from '../lib/journey.ts';
import {validateState} from '../lib/account-validation.ts';
import {recommend,moneyValue} from '../lib/recommendations.ts';
function setup(){const s=emptyState();Object.assign(s.profile,{preferences:['Indoors'],interests:['Music'],needs:['Nothing to add'],strengths:['I keep routines'],activity:'Mostly seated',rhythms:['Calls'],window:'It varies'});return s;}
test('every launch region completes setup → accept → confirmed receipt → validated account state without inventing savings',()=>{for(const region of regions){let s=setup();Object.assign(s.profile,regionChange(region.code));assert.equal(completeProfile(s.profile),true);assert.equal(accept(s,0),s);s.demo=true;s=accept(s,0);assert.equal(s.entries[0].currency,region.currency);const cost={ideaId:0,currency:region.currency,usualCents:1500,moveCents:450,updatedAt:new Date().toISOString()};s.costs=[cost];assert.equal(moneyValue({id:0},s).cents,1050);assert.equal(receipt(s.entries,'Today',region.currency).money,0);s=finish(s,s.entries[0].id,{minutes:18,outside:true,connecting:false,worthwhile:true,moneyCents:1050});const restored=restore(JSON.stringify(validateState(s)));assert.equal(restored.profile.country,region.code);assert.equal(receipt(restored.entries,'Today',region.currency).money,1050);assert.match(formatMoney(1050,region.currency,region.code),new RegExp(region.currency));}});
test('changing region affects future currency only, does not convert history or change PINS ranking',()=>{let s=setup();const before=recommend(s,new Date('2026-10-05T12:00:00Z')).map(r=>[r.idea.id,r.score]);s.demo=true;s=accept(s,0);s=finish(s,s.entries[0].id,{minutes:10,outside:false,connecting:false,worthwhile:true,moneyCents:500});Object.assign(s.profile,regionChange('SG'));assert.equal(s.entries[0].currency,'AUD');assert.equal(receipt(s.entries,'Today','SGD').money,0);assert.equal(receipt(s.entries,'Today','AUD').money,500);const neutral=setup();Object.assign(neutral.profile,regionChange('ZA'));assert.deepEqual(recommend(neutral,new Date('2026-10-05T12:00:00Z')).map(r=>[r.idea.id,r.score]),before);assert.throws(()=>regionChange('XX'))});
test('money parsing uses exact cents and refuses ambiguous, negative, nonfinite and overprecision inputs',()=>{assert.equal(parseMoney('10.05'),1005);assert.equal(parseMoney('0'),0);assert.equal(parseMoney('1000.00'),100000);for(const value of ['','-1','1.001','1,20','1e3','Infinity','1000.01','$10'])assert.equal(parseMoney(value),null);assert.equal(savingFromCost({usualCents:100,moveCents:150}),0)});
test('setup resumes at the first required gap, optional country and name do not gate completion',()=>{const s=emptyState();assert.equal(resumeSetup(s.profile),0);s.profile.preferences=['Indoors'];assert.equal(resumeSetup(s.profile),2);s.profile.interests=['Music'];assert.equal(resumeSetup(s.profile),3);Object.assign(s.profile,setup().profile);assert.equal(completeProfile(s.profile),true);assert.equal(resumeSetup(s.profile),0);delete s.profile.country;s.profile.name='';assert.equal(completeProfile(s.profile),true);assert.match(setupInstruction(5),/all three/)});
test('cloud validator preserves legacy accounts and rejects forged/duplicate regional cost records',()=>{assert.deepEqual(validateState(emptyState()),emptyState());const s=setup();s.profile.country='SG';s.profile.currency='SGD';s.costs=[{ideaId:0,currency:'SGD',usualCents:500,moveCents:100,updatedAt:new Date().toISOString()}];assert.equal(validateState(s).costs[0].currency,'SGD');assert.throws(()=>validateState({...s,costs:[...s.costs,...s.costs]}));assert.throws(()=>validateState({...s,costs:[{...s.costs[0],ideaId:9999999}]}));assert.throws(()=>validateState({...s,profile:{...s.profile,country:'XX'}}));assert.throws(()=>validateState({...s,costs:[{...s.costs[0],moveCents:-10}]}))});
