import test from 'node:test';
import assert from 'node:assert/strict';
import {snapshotSchema,suggestedThreshold,todayMovement,enoughToday,movementEvidenceSchema,dateAt} from '../lib/movement.ts';
import {emptyState,finish} from '../lib/journey.ts';
import {validateState} from '../lib/account-validation.ts';
const now=new Date('2026-10-05T12:00:00Z');
function readings(){return {source:'apple-health',timezone:'UTC',readAt:now.toISOString(),days:[{date:'2026-10-05',steps:1000,exerciseMinutes:0},...Array.from({length:14},(_,i)=>({date:new Date(Date.UTC(2026,9,4-i)).toISOString().slice(0,10),steps:i<7?(i+1)*100:null,exerciseMinutes:null}))]};}
test('baseline requires seven readable prior days and excludes today and missing records',()=>{const s=readings();assert.equal(suggestedThreshold(s,'steps',now),400);assert.equal(suggestedThreshold(s,'exerciseMinutes',now),null);s.days[1].steps=null;assert.equal(suggestedThreshold(s,'steps',now),null)});
test('fresh current-day readings alone can quiet suggestions',()=>{const s=readings(),settings={metric:'steps',threshold:900};assert.equal(enoughToday(s,settings,now),true);assert.equal(enoughToday({...s,readAt:'2026-10-04T12:00:00Z'},settings,now),false);assert.equal(enoughToday(s,{metric:'exerciseMinutes',threshold:1},now),false);assert.equal(enoughToday(s,{metric:'steps',threshold:null},now),false);assert.equal(todayMovement(s,new Date('2026-10-06T00:01:00Z')),null)});
test('timezone boundaries use local days, including DST',()=>{assert.equal(dateAt(new Date('2026-11-01T05:30:00Z'),'America/New_York'),'2026-11-01');assert.equal(dateAt(new Date('2026-10-05T01:00:00Z'),'America/Los_Angeles'),'2026-10-04')});
test('unknown samples, duplicate dates, invalid timezone and nonfinite data are rejected',()=>{const s=readings();assert.throws(()=>snapshotSchema.parse({...s,heartRate:80}));assert.throws(()=>snapshotSchema.parse({...s,timezone:'wrong'}));assert.throws(()=>snapshotSchema.parse({...s,days:[s.days[0],s.days[0]]}));assert.throws(()=>snapshotSchema.parse({...s,days:[{...s.days[0],steps:NaN}]}));assert.throws(()=>movementEvidenceSchema.parse({source:'health-connect',start:now.toISOString(),end:now.toISOString(),readAt:now.toISOString(),steps:0,exerciseMinutes:null}))});
test('health evidence never completes a move; confirmed outcomes keep evidence and reflection',()=>{const s=emptyState(),start='2026-10-05T10:00:00Z',end='2026-10-05T10:15:00Z';s.entries=[{id:'one',ideaId:0,status:'accepted',acceptedAt:start,currency:'AUD',movementWindow:{start,end},movementEvidence:{source:'apple-health',start,end,readAt:now.toISOString(),steps:500,exerciseMinutes:null}}];assert.equal(validateState(s).entries[0].status,'accepted');const result=finish(s,'one',{minutes:15,moneyCents:0,outside:false,connecting:false,worthwhile:true,additionalMovement:'more'});assert.equal(validateState(result).entries[0].additionalMovement,'more');assert.throws(()=>validateState({...s,entries:[{...s.entries[0],movementWindow:{start:'2026-10-05T11:00:00Z',end}}]}));assert.equal(validateState(emptyState()).movementSettings,undefined)});
