import test from 'node:test';
import assert from 'node:assert/strict';
import {emptyState,accept,finish,restore} from '../lib/journey.ts';
import {catalogue,byId,promised} from '../lib/ideas.ts';
import {recommend,eligible,moneyValue,learnedWeights} from '../lib/recommendations.ts';
import {aiContext,validateCandidates} from '../lib/ai-ideas.ts';
import {validateState} from '../lib/account-validation.ts';
const now=new Date(2026,9,5,12);
function profile(){const s=emptyState();s.profile={...s.profile,preferences:['Outside'],interests:['Podcasts'],needs:['Nothing to add'],strengths:['I enjoy learning'],activity:'Mostly sitting',rhythms:['Calls','Podcasts','Work'],window:'Daytime'};s.demo=true;return s;}
test('the complete library keeps stable legacy IDs and supports later ideas across save/accept/confirm/restore',()=>{assert.equal(catalogue.length,44);assert.equal(new Set(catalogue.map(i=>i.id)).size,44);assert.equal(byId(0).image,'dinner');assert.equal(byId(1).image,'call');let s=profile();const idea=catalogue.find(i=>i.key==='garden-podcast');s.saved=[idea.id];s=accept(s,idea.id);assert.deepEqual(s.entries[0].predicted,promised(idea));s=finish(s,s.entries[0].id,{minutes:20,outside:true,connecting:false,worthwhile:true,moneyCents:0,gave:['experience','task_completed']});assert.equal(validateState(restore(JSON.stringify(s))).entries[0].ideaId,idea.id);});
test('complete setup is mandatory and visual/name differences never change rankings or scores',()=>{assert.deepEqual(recommend(emptyState(),now),[]);const a=profile(),b=profile();b.profile.visual=['City streets','Country settings'];b.profile.name='Different';assert.deepEqual(recommend(a,now),recommend(b,now));});
test('access, safety, weather, energy and time constraints apply before scores',()=>{const s=profile();s.profile.needs=['Physical comfort / accessibility'];const accessible=recommend(s,now);assert.ok(accessible.length>0);assert.ok(accessible.every(r=>r.idea.movementMode==='seated'));s.profile.needs=['Safety matters','Weather / heat','Low energy / tired','Not enough time'];assert.ok(recommend(s,now).every(r=>!r.idea.outdoor&&r.idea.effort==='gentle'&&r.idea.minutes<=20&&r.idea.extraMin<=5));s.tuning={extraMinutes:0,travel:'varies',hidden:[]};assert.ok(recommend(s,now).every(r=>r.idea.extraMin<=0));});
test('positive and negative confirmed feedback adjust scores; Not today does not punish fit',()=>{const s=profile(),target=byId(1),base=recommend(s,now).find(r=>r.idea.id===1).score;const e={id:'try',ideaId:1,status:'completed',acceptedAt:now.toISOString(),completedAt:now.toISOString(),minutes:12,outside:true,connecting:true,worthwhile:true,moneyCents:0,currency:'AUD',predicted:promised(target)};s.entries=[e];assert.ok(recommend(s,now).find(r=>r.idea.id===1).score>base);s.entries=[{...e,status:'not-today'}];assert.equal(recommend(s,now).find(r=>r.idea.id===1).score,base);s.entries=[{...e,worthwhile:false}];assert.ok(recommend(s,now).find(r=>r.idea.id===1).score<base);});
test('money is an explicit source assumption in AUD or an actual prior saving in the selected currency',()=>{const s=profile();assert.equal(moneyValue(byId(0),s).cents,699);s.profile.currency='GBP';assert.equal(moneyValue(byId(0),s),null);assert.equal(moneyValue(byId(1),s),null);s.entries=[{id:'done',ideaId:0,status:'completed',currency:'GBP',moneyCents:350}];assert.equal(moneyValue(byId(0),s).cents,350);});
test('hidden ideas disappear, passing remains weak, and more than three ideas remain browsable',()=>{const s=profile(),list=recommend(s,now);assert.ok(list.length>3);const id=list[0].idea.id;s.passes=[{ideaId:id,at:now.toISOString()}];assert.ok(recommend(s,now).some(r=>r.idea.id===id));s.tuning={extraMinutes:15,travel:'varies',hidden:[id]};assert.ok(!recommend(s,now).some(r=>r.idea.id===id));});
test('AI context omits identity, visual preferences, photos and companion names',()=>{const s=profile();s.profile.name='PRIVATE_NAME';s.profile.visual=['PRIVATE_VISUAL'];s.entries=[{status:'completed',id:'x',ideaId:1,worthwhile:true,companions:[{name:'PRIVATE_BUDDY'}]}];const raw=JSON.stringify(aiContext(s,now));for(const marker of ['PRIVATE_NAME','PRIVATE_VISUAL','PRIVATE_BUDDY'])assert.ok(!raw.includes(marker));});
const ai={title:'The quieter way home',hook:'Keep an everyday pause.',category:'work',lifeAnchor:'break',mechanism:'combine',family:'pause',counterfactual:'Remain seated',suggestion:'Try a comfortable seated version.',movementMode:'seated',socialConfiguration:'alone',outdoor:false,effort:'gentle',movementMinutes:999,extraMinutes:-3,money:900,moneySource:'none',output:'',whyThisFits:'Your comfort matters.',fitLabel:'Quiet option',safety:'Choose a familiar movement.',fitScore:10,feasibilityScore:10,discoveryScore:10,predictedWorthIt:10,enjoy:['Solitude'],brief:{experienceBeingSold:'A comfortable pause',desiredEmotion:'Calm',reward:'Space',rewardShown:'A pause in a bright room',activity:'Seated',socialContext:'Alone',setting:'Home',timeOfDay:'Day'}};
test('AI candidates reject malformed or conflicting ideas, clamp claims and deduplicate titles',()=>{const s=profile();const ideas=validateCandidates({candidates:[ai,ai,{...ai,title:''},{...ai,unexpected:true}]},s,now);assert.equal(ideas.length,1);assert.equal(ideas[0].minutes,60);assert.equal(ideas[0].extraMin,0);assert.equal(ideas[0].moneyCents,0);assert.ok(ideas[0].id>=1000);s.generated=ideas;assert.deepEqual(validateCandidates({candidates:[ai]},s,now),[]);const access=profile();access.profile.needs=['Physical comfort / accessibility'];assert.deepEqual(validateCandidates({candidates:[{...ai,movementMode:'walk'}]},access,now),[]);});
test('learning uses only explicit confirmed returns and schema rejects impossible combined time',()=>{const s=profile();s.entries=[{id:'x',ideaId:1,status:'completed',acceptedAt:now.toISOString(),completedAt:now.toISOString(),minutes:12,outside:true,connecting:true,worthwhile:true,moneyCents:0,currency:'AUD',predicted:['social','task_completed','time_combined']}];assert.equal(learnedWeights(s).social.got,1);assert.equal(learnedWeights(s).task_completed.promised,0);s.entries[0].timeCombined=20;assert.throws(()=>validateState(s));});

test('the first five matches include at most two walk variants when alternatives exist',()=>{const list=recommend(profile(),now);assert.ok(list.slice(0,5).filter(r=>r.idea.movementMode==='walk').length<=2);});
