import {signedIn} from '@/lib/supabase/server';
import {sameOrigin} from '@/lib/public-auth';
import {validateState} from '@/lib/account-validation';
import type {SupabaseClient} from '@supabase/supabase-js';
export const dynamic='force-dynamic';
const json=(data:unknown,status=200)=>Response.json(data,{status,headers:{'Cache-Control':'private, no-store'}});
async function completed(db:SupabaseClient,userId:string){const {data,error}=await db.from('enough_accounts').select('state_json').eq('user_id',userId).maybeSingle();if(error)throw error;return data?validateState(data.state_json).entries.filter(e=>e.status==='completed').map(e=>e.id):[];}
export async function GET(req:Request){try{const {db,user}=await signedIn();if(!user)return json({error:'Sign in to view photos.'},401);const id=new URL(req.url).searchParams.get('id'),ids=await completed(db,user.id);
 if(id){const {data:p,error}=await db.from('enough_photos').select('*').eq('id',id).eq('user_id',user.id).maybeSingle();if(error)throw error;if(!p||!ids.includes(p.entry_id))return json({error:'Photo not found.'},404);const {data,error:storageError}=await db.storage.from('enough-photos').download(p.object_key);if(storageError||!data)return json({error:'Photo not found.'},404);return new Response(data,{headers:{'Content-Type':'image/jpeg','Cache-Control':'private, no-store','X-Content-Type-Options':'nosniff'}});}
 const {data,error}=await db.from('enough_photos').select('id,entry_id,caption,created_at').eq('user_id',user.id).order('created_at',{ascending:false});if(error)throw error;return json({photos:data.filter(p=>ids.includes(p.entry_id))});
 }catch{return json({error:'Your photos could not be loaded. Try again.'},503)}}
export async function POST(req:Request){if(!sameOrigin(req))return json({error:'Request origin is not allowed.'},403);try{const {db,user}=await signedIn();if(!user)return json({error:'Sign in to add photos.'},401);
 if(Number(req.headers.get('content-length'))>3*1024*1024)return json({error:'Choose a smaller photo.'},413);const form=await req.formData(),file=form.get('photo'),entryId=form.get('entryId'),caption=form.get('caption');
 if(!(file instanceof File)||file.type!=='image/jpeg'||file.size>2*1024*1024||file.size<4||typeof entryId!=='string'||typeof caption!=='string'||caption.length>200)return json({error:'Choose a JPEG photo under 2 MB and a caption under 200 characters.'},400);
 if(!(await completed(db,user.id)).includes(entryId))return json({error:'Save a confirmed outcome before adding photos.'},409);
 const {count,error:countError}=await db.from('enough_photos').select('id',{count:'exact',head:true}).eq('user_id',user.id).eq('entry_id',entryId);if(countError)throw countError;if((count||0)>=12)return json({error:'Up to twelve photos per activity.'},400);
 const bytes=await file.arrayBuffer(),magic=new Uint8Array(bytes);if(magic[0]!==255||magic[1]!==216||magic[2]!==255)return json({error:'This file is not a JPEG photo.'},400);
 const id=crypto.randomUUID(),key=user.id+'/'+id+'.jpg';const {error:uploadError}=await db.storage.from('enough-photos').upload(key,bytes,{contentType:'image/jpeg',upsert:false});if(uploadError)throw uploadError;
 const {data,error}=await db.from('enough_photos').insert({id,user_id:user.id,entry_id:entryId,object_key:key,caption:caption.trim()}).select('id,entry_id,caption,created_at').single();if(error){await db.storage.from('enough-photos').remove([key]);throw error}return json({photo:data},201);
 }catch{return json({error:'Your photo could not be saved. Please try again.'},503)}}
export async function DELETE(req:Request){if(!sameOrigin(req))return json({error:'Request origin is not allowed.'},403);try{const {db,user}=await signedIn();if(!user)return json({error:'Sign in first.'},401);const {id}=await req.json();if(typeof id!=='string')return json({error:'Choose a photo.'},400);const {data:p,error}=await db.from('enough_photos').select('object_key').eq('id',id).eq('user_id',user.id).maybeSingle();if(error)throw error;if(!p)return json({error:'Photo not found.'},404);const removed=await db.storage.from('enough-photos').remove([p.object_key]);if(removed.error)throw removed.error;const deleted=await db.from('enough_photos').delete().eq('id',id).eq('user_id',user.id);if(deleted.error)throw deleted.error;return json({deleted:true});}catch{return json({error:'Your photo could not be removed. Try again.'},503)}}
