"use client";
import {useEffect,useRef,useState} from 'react';
import type {Evidence} from '@/lib/movement';
import type {Entry} from '@/lib/journey';
import {nativeMovementAvailable,readWindow} from '@/lib/native-movement';
export function ActivityMovement({entry,onChange}:{entry:Entry;onChange:(changes:Partial<Entry>)=>void}){
 const [native,setNative]=useState(false),[preview,setPreview]=useState<Evidence|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState('');useEffect(()=>setNative(nativeMovementAvailable()),[]);
 const request=useRef(0);useEffect(()=>{const clear=()=>{if(document.hidden){request.current++;setPreview(null);setBusy(false)}};document.addEventListener('visibilitychange',clear);return()=>{request.current++;document.removeEventListener('visibilitychange',clear)}},[]);
 const start=()=>{setPreview(null);onChange({movementWindow:{start:new Date().toISOString()},movementEvidence:undefined});setMessage('Movement check started. Finish it when your activity ends.');};
 const end=async()=>{const id=++request.current;const beginning=entry.movementWindow?.start;if(!beginning)return;const finish=new Date().toISOString();if(Date.parse(finish)-Date.parse(beginning)>86400000){setMessage('This check is more than a day old. Start a new one or confirm your activity yourself.');return;}onChange({movementWindow:{start:beginning,end:finish},movementEvidence:undefined});setBusy(true);try{const evidence=await readWindow(beginning,finish);if(id!==request.current||document.hidden)return;setPreview(evidence);setMessage('Movement read. Save it with this activity only if you want to keep it.');}catch{if(id!==request.current)return;setMessage('No movement reading available. Your check-in still works. Connect health data on My Enough or check your phone permissions.');}finally{if(id===request.current)setBusy(false)}};
 return <details className="activity-movement"><summary>Movement check · optional</summary><p>Read movement during this activity. Overlapping movement may belong to something else; you decide what happened.</p>{native?<div className="action-row"><button className="secondary" disabled={busy} onClick={start}>{entry.movementWindow?'Start a new check':'Start movement check'}</button>{entry.movementWindow&&!entry.movementWindow.end&&<button className="secondary" disabled={busy} onClick={end}>{busy?'Reading…':'Finish movement check'}</button>}</div>:<p className="sample-note">Available in the native app after connecting health data. Here, use your own confirmation.</p>}{entry.movementWindow&&<p className="sample-note">Started {new Date(entry.movementWindow.start).toLocaleString()}{entry.movementWindow.end&&` · ended ${new Date(entry.movementWindow.end).toLocaleTimeString()}`}</p>}<MovementEvidence entry={preview?{...entry,movementEvidence:preview}:entry}/>{preview&&<button className="secondary" onClick={()=>{onChange({movementEvidence:preview});setPreview(null);setMessage('Reading saved with this activity. You still need to confirm what happened.')}}>Save reading with this activity</button>}{entry.movementEvidence&&<button className="text-button" onClick={()=>onChange({movementEvidence:undefined})}>Remove saved movement reading</button>}<p role="status">{message}</p></details>
}
export function MovementEvidence({entry}:{entry:Entry}){const data=entry.movementEvidence;if(!data)return null;return <p className="sample-note">{data.source==='apple-health'?'Apple Health':'Health Connect'} recorded {data.steps===null?'no readable step total':`${Math.round(data.steps)} steps`} and {data.exerciseMinutes===null?'no readable exercise time':`${Math.round(data.exerciseMinutes)} exercise minutes`} during your check. This supports your own confirmation; it does not verify completion.</p>}
