"use client";
import {useEffect,useRef,useState} from 'react';
import {Activity} from 'lucide-react';
import {LiveMotionPanel} from './movement-panel';
import {connectMovement,readMovement,disconnectMovement,nativeMovementAvailable} from '@/lib/native-movement';
import {suggestedThreshold,todayMovement,enoughToday,type Snapshot,type MovementSettings} from '@/lib/movement';
export function MovementPanel({settings,onChange}:{settings?:MovementSettings;onChange:(s:MovementSettings)=>void}){
 const [native,setNative]=useState(false),[snapshot,setSnapshot]=useState<Snapshot|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[connected,setConnected]=useState(false),[threshold,setThreshold]=useState('');
 const request=useRef(0);
 const config=settings||{metric:'steps',threshold:null};
 useEffect(()=>{setNative(nativeMovementAvailable());},[]);
 useEffect(()=>{setThreshold(config.threshold?.toString()||'');},[config.threshold]);
 useEffect(()=>{const clear=()=>{if(document.hidden){request.current++;setSnapshot(null);setBusy(false)}};document.addEventListener('visibilitychange',clear);const timer=setInterval(()=>setSnapshot(s=>todayMovement(s)?s:null),60000);return()=>{document.removeEventListener('visibilitychange',clear);clearInterval(timer);request.current++}},[]);
 const refresh=async()=>{const id=++request.current;setBusy(true);setMessage('');try{const next=connected?await readMovement():await connectMovement();if(id!==request.current||document.hidden)return;setSnapshot(next);setConnected(true);if(!next.days.some(d=>d.steps!==null||d.exerciseMinutes!==null))setMessage('No readable records yet. Access may be off, or your health app may have no records. You can still confirm moves yourself.');}catch{if(id!==request.current)return;setSnapshot(null);setMessage('Movement data could not be read. Check health permissions in your phone settings, then try again. Manual check-ins remain available.');}finally{if(id===request.current)setBusy(false)}};
 const today=todayMovement(snapshot),suggested=snapshot?suggestedThreshold(snapshot,config.metric):null;
 return <section className="movement-panel" aria-labelledby="movement-title"><div className="movement-title"><Activity size={22}/><h2 id="movement-title">Your movement today</h2></div><div className="movement-metrics"><div><strong>{today?.steps?.toLocaleString()??'—'}</strong><span>Daily steps</span></div><div><strong>{today?.exerciseMinutes===null||today?.exerciseMinutes===undefined?'—':Math.round(today.exerciseMinutes)}</strong><span>Exercise Minutes</span></div></div>
 {native?<><p className="sensor-note">Read-only access to steps and exercise time. Your daily readings stay in memory and clear when you leave this screen.</p><div className="action-row"><button className="secondary" disabled={busy} onClick={refresh}>{busy?'Reading…':connected?'Refresh movement':'Connect health data'}</button>{connected&&<button className="text-button" disabled={busy} onClick={async()=>{request.current++;await disconnectMovement();setSnapshot(null);setConnected(false);setMessage('Reading stopped. To revoke health permission, use your phone’s health settings.')}}>Disconnect</button>}</div></>:<p className="sensor-note">Apple Health and Android Health Connect need the native ENOUGH app. This browser cannot read those daily totals. You can still plan and confirm your moves here.</p>}
 <p role="status">{message}</p>{snapshot&&<p className="sensor-note">{snapshot.source==='apple-health'?'Apple Health exercise time':'Health Connect recorded exercise sessions'} · updated {new Date(snapshot.readAt).toLocaleTimeString()}. These measures differ between devices and may not include everyday movement.</p>}
 <details className="health-settings"><summary>Your enough for today</summary><p>Choose when ENOUGH should stay quiet. This is your preference, not a health target. You can always keep exploring.</p><label className="field">Measure<select value={config.metric} onChange={e=>onChange({metric:e.target.value as MovementSettings['metric'],threshold:null})}><option value="steps">Daily steps</option><option value="exerciseMinutes">Exercise Minutes</option></select></label><p>{suggested===null?'We need at least seven readable days from the last fortnight to suggest your usual amount.':`Your usual amount: ${suggested.toLocaleString()} ${config.metric==='steps'?'steps':'minutes'} (median of readable days).`}</p>{suggested!==null&&<button className="secondary" onClick={()=>onChange({...config,threshold:suggested})}>Use my usual amount</button>}<label className="field">My quiet threshold · optional<input type="number" min="1" max={config.metric==='steps'?100000:1440} step="1" value={threshold} onChange={e=>setThreshold(e.target.value)}/></label><button className="secondary" onClick={()=>{const n=Number(threshold);if(threshold===''||Number.isInteger(n)&&n>0&&n<=(config.metric==='steps'?100000:1440)){onChange({...config,threshold:threshold===''?null:n});setMessage('Your quiet preference is saved.')}else setMessage('Enter a positive whole number within the field limits.')}}>Save preference</button></details>
 {enoughToday(snapshot,config)&&<p className="quiet-message" role="status">You’ve reached your chosen amount today. No need for another suggestion. Explore whenever you feel like it.</p>}
 <details><summary>Try your phone’s live motion signal</summary><LiveMotionPanel/></details></section>
}
