"use client";
import {useEffect,useRef,useState} from 'react';
import QRCode from 'qrcode';
import jsQR from 'jsqr';
import {meetingCode,readMeetingCode,addCompanion,type Companion} from '@/lib/move-memories';
export function MeetingCheckin({people=[],name='',onChange}:{people?:Companion[];name?:string;onChange:(p:Companion[])=>void}){
 const [open,setOpen]=useState(false),[myName,setMyName]=useState(name),[qr,setQr]=useState(''),[manual,setManual]=useState(''),[candidate,setCandidate]=useState(''),[error,setError]=useState(''),[scanning,setScanning]=useState(false);
 const video=useRef<HTMLVideoElement>(null),stream=useRef<MediaStream|null>(null),timer=useRef<ReturnType<typeof setInterval>|null>(null),generation=useRef(0);
 const stop=()=>{generation.current++;if(timer.current)clearInterval(timer.current);timer.current=null;stream.current?.getTracks().forEach(t=>t.stop());stream.current=null;if(video.current)video.current.srcObject=null;setScanning(false)};
 useEffect(()=>{const hide=()=>{if(document.hidden)stop()};document.addEventListener('visibilitychange',hide);return()=>{generation.current++;if(timer.current)clearInterval(timer.current);stream.current?.getTracks().forEach(t=>t.stop());document.removeEventListener('visibilitychange',hide)}},[]);
 const receive=(raw:string)=>{try{setCandidate(readMeetingCode(raw));setError('');stop()}catch(e){setError((e as Error).message)}};
 const scan=async()=>{setError('');if(!navigator.mediaDevices?.getUserMedia){setError('Camera scanning is unavailable. Upload a QR picture or add their name instead.');return;}stop();const token=++generation.current;setScanning(true);try{const s=await navigator.mediaDevices.getUserMedia({video:{facingMode:'environment'},audio:false});if(token!==generation.current){s.getTracks().forEach(t=>t.stop());return}stream.current=s;if(video.current){video.current.srcObject=s;await video.current.play()}const canvas=document.createElement('canvas');timer.current=setInterval(()=>{const v=video.current;if(!v||v.readyState<2)return;const scale=Math.min(1,640/v.videoWidth);canvas.width=Math.round(v.videoWidth*scale);canvas.height=Math.round(v.videoHeight*scale);const c=canvas.getContext('2d',{willReadFrequently:true});if(!c)return;c.drawImage(v,0,0,canvas.width,canvas.height);const pixels=c.getImageData(0,0,canvas.width,canvas.height);const found=jsQR(pixels.data,canvas.width,canvas.height);if(found)receive(found.data)},350)}catch{stop();setError('The camera could not open. Check permission, upload a QR picture, or add their name.')}};
 const file=async(f?:File)=>{if(!f)return;stop();try{if(f.size>15*1024*1024)throw Error('Choose a QR picture under 15 MB.');const image=await createImageBitmap(f),canvas=document.createElement('canvas');const scale=Math.min(1,1600/Math.max(image.width,image.height));canvas.width=Math.round(image.width*scale);canvas.height=Math.round(image.height*scale);const c=canvas.getContext('2d',{willReadFrequently:true})!;c.drawImage(image,0,0,canvas.width,canvas.height);image.close();const pixels=c.getImageData(0,0,canvas.width,canvas.height),found=jsQR(pixels.data,canvas.width,canvas.height);if(!found)throw Error('No readable QR found. Try a clearer picture or enter their name.');receive(found.data)}catch(e){setError((e as Error).message)}};
 const add=(n:string,source:'qr'|'manual')=>{try{onChange(addCompanion(people,n,source));setCandidate('');setManual('');setError('')}catch(e){setError((e as Error).message)}};
 return <section className="meeting-panel"><div className="meeting-heading"><h4>Who joined you?</h4><button className="text-button" onClick={()=>{if(open)stop();setOpen(!open)}}>{open?'Close check-in':'Add a name / scan QR'}</button></div>{people.length>0&&<ul className="people-chips">{people.map(p=><li key={p.id}><span>{p.name}<small>{p.source==='qr'?'QR check-in':'Added by you'}</small></span><button aria-label={'Remove '+p.name} onClick={()=>onChange(people.filter(x=>x.id!==p.id))}>×</button></li>)}</ul>}{open&&<div className="meeting-controls"><p>Ask before keeping someone’s name. A first name or nickname is enough. These notes stay private.</p><div className="action-row"><button className="secondary" onClick={scanning?stop:scan}>{scanning?'Stop camera':'Scan their QR'}</button><label className="secondary file-button">Read a QR picture<input type="file" accept="image/*" onChange={e=>{void file(e.target.files?.[0]);e.target.value=''}}/></label></div><video ref={video} playsInline muted className={scanning?'qr-camera':'qr-camera hidden-camera'} aria-label="QR scanning camera"/>{candidate&&<div className="checkin-confirm"><p>Did you meet <strong>{candidate}</strong> during this activity?</p><button className="primary" onClick={()=>add(candidate,'qr')}>Yes, add to this move</button><button className="text-button" onClick={()=>setCandidate('')}>Cancel</button></div>}<div className="manual-checkin"><label className="field">Or add their name<input maxLength={60} value={manual} onChange={e=>setManual(e.target.value)} placeholder="First name or nickname"/></label><button className="secondary" onClick={()=>add(manual,'manual')}>Add name</button></div><details className="my-name-qr"><summary>Show my name QR</summary><p>Let someone scan your chosen name. This code contains only that name; it does not open your profile.</p><label className="field">Name to share<input maxLength={60} value={myName} onChange={e=>{setMyName(e.target.value);setQr('')}}/></label><button className="secondary" onClick={async()=>{try{setQr(await QRCode.toDataURL(meetingCode(myName),{width:280,margin:4,errorCorrectionLevel:'M'}));setError('')}catch(e){setError((e as Error).message)}}}>Show QR</button>{qr&&<img className="name-qr" src={qr} alt={'Name QR for '+myName}/>}</details><p className="sample-note">QR check-ins are voluntary name exchanges, not verified identity or proof of location. They do not send invitations or count a completed move.</p>{error&&<p role="alert" className="storage-alert">{error}</p>}</div>}</section>
}
