"use client";
import {useState} from 'react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from './ui/dialog';
import {parseMoney,formatMoney,savingFromCost,type Cost} from '@/lib/regions';
export function MoveCosts({ideaId,title,currency,country,cost,onSave,onRemove}:{ideaId:number;title:string;currency:string;country?:string;cost?:Cost;onSave:(c:Cost)=>void;onRemove:()=>void}){
 const [open,setOpen]=useState(false),[usual,setUsual]=useState(''),[move,setMove]=useState(''),[error,setError]=useState('');
 const launch=()=>{setUsual(cost?(cost.usualCents/100).toFixed(2):'');setMove(cost?(cost.moveCents/100).toFixed(2):'');setError('');setOpen(true)};
 const usualCents=parseMoney(usual),moveCents=parseMoney(move);const valid=usualCents!==null&&moveCents!==null;
 const save=()=>{if(!valid){setError('Enter both costs from 0 to 1,000, with up to two decimal places.');return}onSave({ideaId,currency:currency as Cost['currency'],usualCents,moveCents,updatedAt:new Date().toISOString()});setOpen(false)};
 return <><button className="text-button cost-link" onClick={launch}>{cost?'Edit my cost calculation':'Calculate Money Saved with my costs'}</button><Dialog open={open} onOpenChange={setOpen}><DialogContent className="enough-modal"><DialogTitle>Your costs for this move</DialogTitle><DialogDescription>{title}. Use the costs you would actually pay, including any extra costs. This calculation stays separate from confirmed money in My Wins.</DialogDescription><form onSubmit={e=>{e.preventDefault();save()}}><label className="field">What would you normally spend? ({currency})<input required type="text" inputMode="decimal" value={usual} onChange={e=>setUsual(e.target.value)}/></label><label className="field">What would this move cost in total? ({currency})<input required type="text" inputMode="decimal" value={move} onChange={e=>setMove(e.target.value)}/></label>{valid&&<div className="cost-result" role="status"><span>Money Saved</span><strong>{formatMoney(savingFromCost({ideaId,currency:currency as Cost['currency'],usualCents,moveCents,updatedAt:new Date().toISOString()}),currency,country)}</strong><p>{moveCents>usualCents?`This move would cost ${formatMoney(moveCents-usualCents,currency,country)} more. No saving is counted.`:'Your usual cost minus this move’s cost. Only confirm money afterwards if you actually kept it.'}</p></div>}{error&&<p role="alert" className="storage-alert">{error}</p>}<button className="primary" type="submit">Use these costs</button>{cost&&<button className="text-button" type="button" onClick={()=>{onRemove();setOpen(false)}}>Remove my cost calculation</button>}</form></DialogContent></Dialog></>
}
