import {ArrowRight, Zap, Heart, Leaf, Footprints, Wallet, Clock, Search, List, Star, Check, X} from 'lucide-react';
import s from './welcome.module.css';
const experiences=[
 {tag:'CALL MUM',title:'You were going to call anyway.',text:'Take the conversation outside.',image:'call'},
 {tag:'PICK UP DINNER',title:'Collect dinner on the way home.',text:'A short, pleasant detour. Everything in one trip.',image:'dinner'},
 {tag:'PODCAST TIME',title:'Let a podcast lead the way.',text:'Try a new route to a place you haven’t been.',image:'podcast'},
 {tag:'SCHOOL RUN',title:'Let the kids choose the route.',text:'Give them 20 minutes to explore somewhere nearby.',image:'school'}
];
export function Welcome(){return <div className={s.welcome}>
 <a className={s.skip} href="#welcome-main">Skip to content</a>
 <header className={s.nav}><a href="/" aria-label="ENOUGH home"><img src="/logo.svg" alt="ENOUGH"/></a><nav aria-label="Welcome navigation"><a href="/" aria-current="page">Home</a><a href="#moves">Find ideas</a><a href="#moves">Saved</a><a href="#pins">Your life</a><a href="#wins">Progress</a></nav><a className={s.open} href="#enough">Open ENOUGH <ArrowRight size={17}/></a></header>
 <main id="welcome-main">
 <section className={s.hero}><img className={s.heroPhoto} src="/images/welcome-hero.webp" alt="A woman enjoying a coffee beside the harbour at sunset" fetchPriority="high"/><div className={s.heroCopy}><h1>Less sacrifice.<br/>More life.</h1><p>Movement that gives back.</p><a className={s.primary} href="#moves">Try ENOUGH <ArrowRight size={19}/></a><div className={s.benefits}>{[[Zap,'More energy for what you love'],[Heart,'Fits your life and priorities'],[Leaf,'Real ideas for real days']].map(([Icon,text])=>{const I=Icon as typeof Zap;return <div key={String(text)}><I size={25}/><span>{String(text)}</span></div>})}</div></div></section>
 <div className={s.sections}>
 <section className={`${s.glass} ${s.problem}`}><span className={s.kicker}>THE PROBLEM</span><h2>Want to exercise more.<br/><span>Don’t want another thing to do?</span></h2></section>
 <section className={`${s.glass} ${s.difference}`}><div><span className={s.kicker}>HOW IT’S DIFFERENT</span><h2>This is not a fitness app.</h2><p>A fitness app hands you a plan and asks for your time. ENOUGH looks at the time you’re already spending.</p><a className={s.secondary} href="#how-it-works">See how it works <ArrowRight size={18}/></a></div><div className={s.comparison}><div><span className={s.kicker}>A FITNESS APP</span><ul>{['Gives you a plan','Adds another thing to do','Focuses on workouts','Takes dedicated time','Easy to drop'].map(x=><li key={x}><X size={16}/>{x}</li>)}</ul></div><div><span className={s.kicker}>ENOUGH</span><ul>{['Finds opportunities in your day','Fits what you already do','Builds movement into real life','No dedicated exercise time','Ideas you’ll actually do again'].map(x=><li key={x}><Check size={16}/>{x}</li>)}</ul></div></div></section>
 <section className={`${s.glass} ${s.ideas}`}><span className={s.kicker}>THE IDEA</span><h2>There’s another way through.</h2><p>ENOUGH finds movement inside things you’re already doing.</p><div className={s.cards}>{experiences.map((x,i)=><a href="#moves" className={s.card} key={x.tag}><img src={'/images/welcome-'+x.image+'.webp'} alt={['A woman enjoying an outdoor phone call','A man picking up fresh produce at a market','A woman listening to a podcast by the water','A mother and daughter walking home together'][i]} loading="lazy"/><div><span className={s.kicker}>{x.tag}</span><h3>{x.title}</h3><p>{x.text}</p><span className={s.arrow}><ArrowRight size={18}/><span className={s.sr}>Explore this kind of idea</span></span></div></a>)}</div><a className={s.primary} href="#moves">See more ideas <ArrowRight size={18}/></a></section>
 <section className={`${s.glass} ${s.results}`}><span className={s.kicker}>WHAT YOU GET BACK</span><h2>A month of ENOUGH, in numbers.</h2><p>An illustrative month — your own results will be personal to you.</p><div className={s.metrics}>{[[Footprints,'3h 48m','Exercise Minutes'],[Wallet,'$42.60','Money Saved from Gym Membership'],[Clock,'0 mins','stolen from your life'],[Heart,'7','things that brought you joy']].map(([Icon,value,label])=>{const I=Icon as typeof Heart;return <div key={String(label)}><I size={28}/><span><strong>{String(value)}</strong><small>{String(label)}</small></span></div>})}</div><small>Example figures, not measured user results. My Wins records only savings you confirm.</small></section>
 <section className={s.breathe}><div className={s.glass}><span className={s.kicker}>A KINDER, SMARTER APPROACH</span><h2>Health without<br/>the homework.</h2><p>No streaks. No guilt. No exercise debt.</p><a className={s.secondary} href="#moves">Try ENOUGH <ArrowRight size={18}/></a></div></section>
 <section id="how-it-works" className={`${s.glass} ${s.how}`}><span className={s.kicker}>HOW IT THINKS</span><h2>One small change to something you’re already doing.</h2><p>Real movement, almost no sacrifice.</p><div className={s.steps}>{[[Search,'Understand','Your life, preferences and what’s getting in the way.'],[List,'Find','Personalised ideas inside your existing plans and routines.'],[Star,'See if it’s worth it','Tell us how an idea worked for you.'],[Check,'Learn','Your answers shape better ideas, over time.']].map(([Icon,title,text],i)=>{const I=Icon as typeof Search;return <div key={String(title)}><I size={30}/><h3>{i+1}. {String(title)}</h3><p>{String(text)}</p></div>})}</div></section>
 </div></main>
 <footer className={s.footer}><div><img src="/logo.svg" alt="ENOUGH"/><p>Less sacrifice. More life.</p></div><nav aria-label="App links"><span>EXPLORE</span><a href="#moves">Find ideas</a><a href="#pins">My Pins</a><a href="#wins">My Wins</a></nav><nav aria-label="Account links"><span>YOUR ENOUGH</span><a href="#enough">Open the app</a><a href="/signin">Sign in</a><a href="/recover">Account recovery</a></nav><p>Movement that fits.<br/>Room for the rest of your life.</p></footer>
 </div>}
