"use client";
import {useEffect,useRef,useState} from 'react';
import Image from 'next/image';
import {ArrowRight,Camera,Footprints,Heart,Images,Plus,Search,Wallet} from 'lucide-react';
import {ChoiceArtwork} from '@/components/pins-options';
import {byId,type Idea} from '@/lib/ideas';
import {ideaCover} from '@/lib/discovery';
import {momentDateLabel} from '@/lib/dashboard';
import {filterMoments,momentFilters,winArtwork,type MomentFilter} from '@/lib/wins';
import {formatMoney} from '@/lib/regions';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import type {Entry} from '@/lib/journey';
type Photo={id:string;entry_id:string;caption:string;created_at:string};
async function preparePhoto(file:File){if(!['image/jpeg','image/png','image/webp'].includes(file.type))throw Error('Choose a JPEG, PNG or WebP photo. Convert HEIC photos to JPEG first.');if(file.size>15*1024*1024)throw Error('Choose a photo under 15 MB.');const image=await createImageBitmap(file);try{if(image.width*image.height>60000000)throw Error('This image is too large. Choose a smaller version.');const scale=Math.min(1,1600/Math.max(image.width,image.height)),canvas=document.createElement('canvas');canvas.width=Math.round(image.width*scale);canvas.height=Math.round(image.height*scale);canvas.getContext('2d')!.drawImage(image,0,0,canvas.width,canvas.height);const blob=await new Promise<Blob>((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(Error('Could not prepare the photo.')),'image/jpeg',.82));if(blob.size>2*1024*1024)throw Error('The prepared photo is too large. Choose a smaller version.');return blob}finally{image.close()}}
export function WinsGallery({entries,titles,cloud,saved,generated=[],country,now,day,onClearDay,onAddWin,onMoment}:{entries:Entry[];titles:Record<number,string>;cloud:boolean;saved:boolean;generated?:Idea[];country?:string;now:number;day:string|null;onClearDay:()=>void;onAddWin:()=>void;onMoment:(id:string)=>void}){
 const [photos,setPhotos]=useState<Photo[]>([]),[status,setStatus]=useState('loading'),[error,setError]=useState(''),[upload,setUpload]=useState(false),[entryId,setEntryId]=useState(''),[caption,setCaption]=useState(''),[files,setFiles]=useState<File[]>([]),[busy,setBusy]=useState(false),[selected,setSelected]=useState<string|null>(null),[confirmDelete,setConfirmDelete]=useState(false),[preview,setPreview]=useState('');
 const [view,setView]=useState<MomentFilter>('All'),[display,setDisplay]=useState<'Moments'|'Photos'>('Moments'),[query,setQuery]=useState(''),[limit,setLimit]=useState(12);
 const touch=useRef<number|null>(null),mounted=useRef(true);useEffect(()=>()=>{mounted.current=false},[]);
 const load=async()=>{if(!cloud){setPhotos([]);setStatus('local');return}setStatus('loading');try{const r=await fetch('/api/photos',{cache:'no-store'}),d=await r.json() as {photos:Photo[];error?:string};if(!r.ok)throw Error(d.error||'Photo storage unavailable.');if(mounted.current){setPhotos(d.photos);setStatus('ready');setError('')}}catch(e){if(mounted.current){setStatus('error');setError((e as Error).message)}}};
 useEffect(()=>{mounted.current=true;void load()},[cloud]);
 useEffect(()=>{if(!files[0]){setPreview('');return}const url=URL.createObjectURL(files[0]);setPreview(url);return()=>URL.revokeObjectURL(url)},[files]);
 const matching=filterMoments(entries,view,query,generated,day,new Date(now)),matchingIds=new Set(matching.map(e=>e.id));
 const visible=cloud?photos.filter(p=>matchingIds.has(p.entry_id)):[],position=visible.findIndex(p=>p.id===selected),photo=position>=0?visible[position]:undefined;
 const startUpload=()=>{setEntryId(matching[0]?.id||entries[0]?.id||'');setError('');setUpload(true)};
 const clearFilters=()=>{setView('All');setQuery('');setLimit(12);onClearDay()};
 const openPhoto=(id:string)=>{setSelected(id);setConfirmDelete(false);setError('')};
 const next=(delta:number)=>{setConfirmDelete(false);setSelected(visible[(position+delta+visible.length)%visible.length]?.id||null)};
 const send=async()=>{if(!entryId||files.length===0){setError('Choose an activity and at least one photo.');return}setBusy(true);setError('');const pending=[...files];let done=0;try{for(const f of pending){const blob=await preparePhoto(f),form=new FormData();form.set('photo',blob,'move.jpg');form.set('entryId',entryId);form.set('caption',caption);const r=await fetch('/api/photos',{method:'POST',body:form}),d=await r.json() as {photo:Photo;error?:string};if(!r.ok)throw Error(d.error||'Photo upload failed.');done++;setPhotos(p=>[d.photo,...p])}setFiles([]);setUpload(false);setCaption('');setDisplay('Photos');clearFilters()}catch(e){setFiles(pending.slice(done));setError(`${done?`${done} photo${done===1?'':'s'} saved. `:''}${(e as Error).message}`)}finally{setBusy(false)}};
 const remove=async()=>{if(!photo)return;setBusy(true);setError('');try{const r=await fetch('/api/photos',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:photo.id})}),d=await r.json() as {error?:string};if(!r.ok)throw Error(d.error||'Photo storage unavailable.');setPhotos(p=>p.filter(x=>x.id!==photo.id));setSelected(null);setConfirmDelete(false)}catch(e){setError((e as Error).message)}finally{setBusy(false)}};
 return <section id="your-win-moments" className="wins-gallery wins-moments-panel" aria-labelledby="wins-moments-heading">
 <div className="gallery-heading"><div><span className="eyebrow">YOUR MOMENTS</span><h2 id="wins-moments-heading">The little things, kept.</h2></div><div className="wins-gallery-actions"><button className="secondary" disabled={!cloud||entries.length===0} onClick={startUpload}><Camera size={17}/>Add photos</button><button className="primary" onClick={onAddWin}><Plus size={17}/>Add a win</button></div></div>
 <p className="wins-gallery-note">All confirmed moves · Private to you. Photos open into your swipeable gallery.</p>
 <div className="wins-gallery-tools"><div className="wins-gallery-mode" aria-label="Moments display">{(['Moments','Photos'] as const).map(v=><button key={v} aria-pressed={display===v} onClick={()=>{setDisplay(v);setSelected(null)}}>{v==='Moments'?<Heart size={16}/>:<Images size={16}/>} {v}</button>)}</div><label className="idea-search"><Search size={18}/><span className="sr-only">Search your moments</span><input type="search" value={query} onChange={e=>{setQuery(e.target.value);setLimit(12);setSelected(null)}} placeholder="Search your moves…"/></label></div>
 <div className="discovery-filters gallery-filters" aria-label="Filter your moments">{momentFilters.map(v=><button key={v} aria-pressed={view===v} onClick={()=>{setView(v);setLimit(12);setSelected(null)}}>{v}</button>)}</div>
 {day&&<div className="wins-day-filter"><span>Moments on {new Date(day+'T12:00:00').toLocaleDateString(undefined,{day:'numeric',month:'long',year:'numeric'})}</span><button className="text-button" onClick={onClearDay}>Show every day</button></div>}
 <p className="wins-gallery-count" role="status">{display==='Moments'?matching.length+' confirmed '+(matching.length===1?'moment':'moments'):visible.length+' private '+(visible.length===1?'photo':'photos')}</p>
 {display==='Moments'?(matching.length?<><div className="win-moment-grid">{matching.slice(0,limit).map(e=>{
   const idea=byId(e.ideaId,generated),memories=cloud?photos.filter(p=>p.entry_id===e.id):[],memory=memories[0];
   return <article className="win-moment-card" key={e.id}><button className="win-moment-cover" onClick={()=>memory?openPhoto(memory.id):onMoment(e.id)} aria-label={(memory?'View photo: ':'See outcome: ')+(memory?.caption||titles[e.ideaId])}>{memory?<img src={'/api/photos?id='+encodeURIComponent(memory.id)} alt={memory.caption||'Your private activity photo'} loading="lazy"/>:<>{idea?.image?<Image src={ideaCover(idea)} alt="" fill sizes="(max-width: 560px) 85vw, (max-width: 1050px) 45vw, 25vw"/>:<ChoiceArtwork label={winArtwork(idea)}/>}<span className="illustration-label">Illustration</span></>}{e.worthwhile&&<span className="moment-worthwhile" aria-label="You said this was worthwhile"><Heart size={17} fill="currentColor"/></span>}{memories.length>1&&<span className="moment-photo-count"><Images size={14}/>{memories.length}</span>}</button>
   <div className="win-moment-body"><button className="win-moment-title" onClick={()=>onMoment(e.id)}><h3>{titles[e.ideaId]||'Your confirmed move'}</h3></button><span className="win-moment-date">{momentDateLabel(e.completedAt!,new Date(now))}</span><div className="win-moment-returns"><span><Footprints size={16}/>{e.minutes||0} min</span><span><Wallet size={16}/>{formatMoney(e.moneyCents||0,e.currency,country)}</span></div><small className="win-moment-money-label">Money kept · confirmed in {e.currency}</small>{memory?.caption?<q className="win-moment-caption">{memory.caption}</q>:<p className="win-moment-reflection">{e.worthwhile?'Worthwhile for you.':'Not worthwhile this time.'}</p>}<button className="widget-link" onClick={()=>onMoment(e.id)}>View outcome<ArrowRight size={15}/></button></div></article>
 })}<button className="win-add-tile" onClick={onAddWin}><Plus size={29}/><strong>Keep another moment.</strong><span>Try an idea, then tell us what happened.</span></button></div>{matching.length>limit&&<button className="secondary wins-show-more" onClick={()=>setLimit(n=>n+12)}>Show more moments</button>}</>:<div className="gallery-empty"><Camera size={29}/><h3>{entries.length?'No moments with those filters.':'Your story starts with a moment.'}</h3><p>{entries.length?'Try another word, day or filter.':'After trying an idea, confirm what happened in My Moves. Your real returns will appear here.'}</p><button className="secondary" onClick={entries.length?clearFilters:onAddWin}>{entries.length?'Clear search and filters':'Find a move to try'}</button></div>):status==='loading'&&cloud?<p role="status">Loading your photos…</p>:visible.length?<div className="photo-tiles">{visible.map(p=><button key={p.id} onClick={()=>openPhoto(p.id)} aria-label={'View photo: '+(p.caption||titles[entries.find(e=>e.id===p.entry_id)!.ideaId])}><img src={'/api/photos?id='+encodeURIComponent(p.id)} alt={p.caption||'Photo from your activity'} loading="lazy"/><span>{titles[entries.find(e=>e.id===p.entry_id)!.ideaId]}</span></button>)}</div>:<div className="gallery-empty"><Camera size={29}/><h3>A private place for your photos.</h3><p>{!cloud?'Sign in and keep your ENOUGH profile to save activity photos.':!entries.length?'Your photos will appear here after you confirm a move.':matching.length?'Keep a photo from one of your confirmed moves.':'No photos match these filters.'}</p>{cloud&&entries.length>0&&<button className="secondary" onClick={matching.length?startUpload:clearFilters}>{matching.length?'Add photos':'Clear search and filters'}</button>}</div>}
 {status==='error'&&<button className="text-button" onClick={load}>Try loading photos again</button>}{error&&!upload&&!photo&&<p role="alert" className="storage-alert">{error}</p>}
 <Dialog open={upload} onOpenChange={v=>{if(!busy)setUpload(v)}}><DialogContent><DialogTitle>Add activity photos</DialogTitle><DialogDescription>Save a moment to a confirmed move. Ask permission before uploading photos of other people.</DialogDescription><label className="field">Activity<select value={entryId} onChange={e=>setEntryId(e.target.value)}>{entries.map(e=><option key={e.id} value={e.id}>{titles[e.ideaId]} · {new Date(e.completedAt!).toLocaleDateString()}</option>)}</select></label><label className="field">Choose photos<input type="file" accept="image/jpeg,image/png,image/webp" multiple disabled={busy} onChange={e=>{const picked=Array.from(e.target.files||[]);if(picked.length>12){setError('Choose up to twelve photos at once.');setFiles([])}else{setFiles(picked);setError('')}e.target.value=''}}/></label>{preview&&<img src={preview} alt="First selected photo preview" className="upload-preview"/>}<label className="field">Caption · optional<input maxLength={200} value={caption} onChange={e=>setCaption(e.target.value)} placeholder="A moment you’d like to remember"/></label><p className="sample-note">{files.length} selected · Up to 12 photos per move. JPEG, PNG or WebP, up to 15 MB each. Photos are resized and location metadata is removed.</p>{!saved&&<p role="status">Wait for your confirmed outcome to finish saving before uploading.</p>}{error&&<p role="alert" className="storage-alert">{error}</p>}<button className="primary" disabled={busy||!saved||!files.length} onClick={send}>{busy?'Saving photos…':'Save photos'}</button></DialogContent></Dialog>
 <Dialog open={!!photo} onOpenChange={v=>{if(!v&&!busy)setSelected(null)}}><DialogContent className="photo-lightbox" onKeyDown={e=>{if(e.key==='ArrowRight')next(1);if(e.key==='ArrowLeft')next(-1)}}><DialogTitle>{photo?titles[entries.find(e=>e.id===photo.entry_id)!.ideaId]:'Your photo'}</DialogTitle><DialogDescription>{position+1} of {visible.length} · Private activity photos</DialogDescription>{photo&&<><img className="full-memory-photo" src={'/api/photos?id='+encodeURIComponent(photo.id)} alt={photo.caption||'Photo from your activity'} onTouchStart={e=>{touch.current=e.touches[0].clientX}} onTouchEnd={e=>{if(touch.current!==null){const d=e.changedTouches[0].clientX-touch.current;if(Math.abs(d)>45)next(d<0?1:-1)}touch.current=null}}/>{photo.caption&&<p>{photo.caption}</p>}{entries.find(e=>e.id===photo.entry_id)?.companions?.length? <p className="photo-company">With {entries.find(e=>e.id===photo.entry_id)!.companions!.map(p=>p.name).join(', ')}</p>:null}<a className="text-button" href={'/api/photos?id='+encodeURIComponent(photo.id)} download="enough-moment.jpg">Save a copy</a><div className="photo-pager"><button className="secondary" disabled={visible.length<2||busy} onClick={()=>next(-1)}>Previous photo</button><span>{position+1} / {visible.length}</span><button className="secondary" disabled={visible.length<2||busy} onClick={()=>next(1)}>Next photo</button></div>{confirmDelete?<div><p>Remove this photo permanently?</p><button className="secondary" disabled={busy} onClick={remove}>{busy?'Removing…':'Remove photo'}</button><button className="text-button" disabled={busy} onClick={()=>setConfirmDelete(false)}>Keep photo</button></div>:<button className="text-button" disabled={busy} onClick={()=>setConfirmDelete(true)}>Remove this photo</button>}{error&&<p role="alert" className="storage-alert">{error}</p>}</>}</DialogContent></Dialog></section>
}
