"use client";
import {useEffect,useRef,useState} from 'react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import type {Entry} from '@/lib/journey';
type Photo={id:string;entry_id:string;caption:string;created_at:string};
async function preparePhoto(file:File){if(!['image/jpeg','image/png','image/webp'].includes(file.type))throw Error('Choose a JPEG, PNG or WebP photo. Convert HEIC photos to JPEG first.');if(file.size>15*1024*1024)throw Error('Choose a photo under 15 MB.');const image=await createImageBitmap(file);try{if(image.width*image.height>60000000)throw Error('This image is too large. Choose a smaller version.');const scale=Math.min(1,1600/Math.max(image.width,image.height)),canvas=document.createElement('canvas');canvas.width=Math.round(image.width*scale);canvas.height=Math.round(image.height*scale);canvas.getContext('2d')!.drawImage(image,0,0,canvas.width,canvas.height);const blob=await new Promise<Blob>((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(Error('Could not prepare the photo.')),'image/jpeg',.82));if(blob.size>2*1024*1024)throw Error('The prepared photo is too large. Choose a smaller version.');return blob}finally{image.close()}}
export function WinsGallery({entries,titles,cloud,saved}:{entries:Entry[];titles:Record<number,string>;cloud:boolean;saved:boolean}){
 const [photos,setPhotos]=useState<Photo[]>([]),[status,setStatus]=useState('loading'),[error,setError]=useState(''),[upload,setUpload]=useState(false),[entryId,setEntryId]=useState(''),[caption,setCaption]=useState(''),[files,setFiles]=useState<File[]>([]),[busy,setBusy]=useState(false),[selected,setSelected]=useState<string|null>(null),[confirmDelete,setConfirmDelete]=useState(false),[preview,setPreview]=useState('');
 const [view,setView]=useState('All moments');
 const touch=useRef<number|null>(null),mounted=useRef(true);useEffect(()=>()=>{mounted.current=false},[]);
 const load=async()=>{if(!cloud){setPhotos([]);setStatus('local');return}setStatus('loading');try{const r=await fetch('/api/photos',{cache:'no-store'}),d=await r.json() as {photos:Photo[];error?:string};if(!r.ok)throw Error(d.error||'Photo storage unavailable.');if(mounted.current){setPhotos(d.photos);setStatus('ready');setError('')}}catch(e){if(mounted.current){setStatus('error');setError((e as Error).message)}}};
 useEffect(()=>{mounted.current=true;void load()},[cloud]);
 useEffect(()=>{if(!files[0]){setPreview('');return}const url=URL.createObjectURL(files[0]);setPreview(url);return()=>URL.revokeObjectURL(url)},[files]);
 const visible=photos.filter(p=>entries.some(e=>e.id===p.entry_id&&(view==='All moments'||view==='Outside'&&e.outside||view==='Together'&&e.connecting))),position=visible.findIndex(p=>p.id===selected),photo=position>=0?visible[position]:undefined;
 const next=(delta:number)=>{setConfirmDelete(false);setSelected(visible[(position+delta+visible.length)%visible.length]?.id||null)};
 const send=async()=>{if(!entryId||files.length===0){setError('Choose an activity and at least one photo.');return}setBusy(true);setError('');const pending=[...files];let done=0;try{for(const f of pending){const blob=await preparePhoto(f),form=new FormData();form.set('photo',blob,'move.jpg');form.set('entryId',entryId);form.set('caption',caption);const r=await fetch('/api/photos',{method:'POST',body:form}),d=await r.json() as {photo:Photo;error?:string};if(!r.ok)throw Error(d.error||'Photo upload failed.');done++;setPhotos(p=>[d.photo,...p])}setFiles([]);setUpload(false);setCaption('')}catch(e){setFiles(pending.slice(done));setError(`${done?`${done} photo${done===1?'':'s'} saved. `:''}${(e as Error).message}`)}finally{setBusy(false)}};
 const remove=async()=>{if(!photo)return;setBusy(true);setError('');try{const r=await fetch('/api/photos',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:photo.id})}),d=await r.json() as {error?:string};if(!r.ok)throw Error(d.error||'Photo storage unavailable.');setPhotos(p=>p.filter(x=>x.id!==photo.id));setSelected(null);setConfirmDelete(false)}catch(e){setError((e as Error).message)}finally{setBusy(false)}};
 return <section className="wins-gallery"><div className="gallery-heading"><div><span className="eyebrow">MOMENTS TO KEEP</span><h2>Your moments</h2></div><button className="secondary" disabled={!cloud||entries.length===0} onClick={()=>{setEntryId(entries[0]?.id||'');setError('');setUpload(true)}}>Add photos</button></div><p className="sample-note">All confirmed moves · Private to you. Tap a tile, then swipe or use the arrows to browse.</p><div className="discovery-filters gallery-filters" aria-label="Filter your photos">{['All moments','Outside','Together'].map(v=><button key={v} aria-pressed={view===v} onClick={()=>{setView(v);setSelected(null)}}>{v}</button>)}</div>{status==='loading'&&cloud?<p role="status">Loading your photos…</p>:visible.length?<div className="photo-tiles">{visible.map(p=><button key={p.id} onClick={()=>{setSelected(p.id);setConfirmDelete(false);setError('')}} aria-label={'View photo: '+(p.caption||titles[entries.find(e=>e.id===p.entry_id)!.ideaId])}><img src={'/api/photos?id='+encodeURIComponent(p.id)} alt={p.caption||'Photo from your activity'} loading="lazy"/><span>{titles[entries.find(e=>e.id===p.entry_id)!.ideaId]}</span></button>)}</div>:<div className="gallery-empty"><p>{!cloud?'Sign in and keep your ENOUGH profile to save activity photos.':entries.length?'Keep a moment from one of your confirmed moves.':'Your photos will appear here after you confirm a move.'}</p></div>}{status==='error'&&<button className="text-button" onClick={load}>Try loading photos again</button>}{error&&!upload&&!photo&&<p role="alert" className="storage-alert">{error}</p>}
 <Dialog open={upload} onOpenChange={v=>{if(!busy)setUpload(v)}}><DialogContent><DialogTitle>Add activity photos</DialogTitle><DialogDescription>Save a moment to a confirmed move. Ask permission before uploading photos of other people.</DialogDescription><label className="field">Activity<select value={entryId} onChange={e=>setEntryId(e.target.value)}>{entries.map(e=><option key={e.id} value={e.id}>{titles[e.ideaId]} · {new Date(e.completedAt!).toLocaleDateString()}</option>)}</select></label><label className="field">Choose photos<input type="file" accept="image/jpeg,image/png,image/webp" multiple disabled={busy} onChange={e=>{const picked=Array.from(e.target.files||[]);if(picked.length>12){setError('Choose up to twelve photos at once.');setFiles([])}else{setFiles(picked);setError('')}e.target.value=''}}/></label>{preview&&<img src={preview} alt="First selected photo preview" className="upload-preview"/>}<label className="field">Caption · optional<input maxLength={200} value={caption} onChange={e=>setCaption(e.target.value)} placeholder="A moment you’d like to remember"/></label><p className="sample-note">{files.length} selected · Up to 12 photos per move. JPEG, PNG or WebP, up to 15 MB each. Photos are resized and location metadata is removed.</p>{!saved&&<p role="status">Wait for your confirmed outcome to finish saving before uploading.</p>}{error&&<p role="alert" className="storage-alert">{error}</p>}<button className="primary" disabled={busy||!saved||!files.length} onClick={send}>{busy?'Saving photos…':'Save photos'}</button></DialogContent></Dialog>
 <Dialog open={!!photo} onOpenChange={v=>{if(!v&&!busy)setSelected(null)}}><DialogContent className="photo-lightbox" onKeyDown={e=>{if(e.key==='ArrowRight')next(1);if(e.key==='ArrowLeft')next(-1)}}><DialogTitle>{photo?titles[entries.find(e=>e.id===photo.entry_id)!.ideaId]:'Your photo'}</DialogTitle><DialogDescription>{position+1} of {visible.length} · Private activity photos</DialogDescription>{photo&&<><img className="full-memory-photo" src={'/api/photos?id='+encodeURIComponent(photo.id)} alt={photo.caption||'Photo from your activity'} onTouchStart={e=>{touch.current=e.touches[0].clientX}} onTouchEnd={e=>{if(touch.current!==null){const d=e.changedTouches[0].clientX-touch.current;if(Math.abs(d)>45)next(d<0?1:-1)}touch.current=null}}/>{photo.caption&&<p>{photo.caption}</p>}{entries.find(e=>e.id===photo.entry_id)?.companions?.length? <p className="photo-company">With {entries.find(e=>e.id===photo.entry_id)!.companions!.map(p=>p.name).join(', ')}</p>:null}<a className="text-button" href={'/api/photos?id='+encodeURIComponent(photo.id)} download="enough-moment.jpg">Save a copy</a><div className="photo-pager"><button className="secondary" disabled={visible.length<2||busy} onClick={()=>next(-1)}>Previous photo</button><span>{position+1} / {visible.length}</span><button className="secondary" disabled={visible.length<2||busy} onClick={()=>next(1)}>Next photo</button></div>{confirmDelete?<div><p>Remove this photo permanently?</p><button className="secondary" disabled={busy} onClick={remove}>{busy?'Removing…':'Remove photo'}</button><button className="text-button" disabled={busy} onClick={()=>setConfirmDelete(false)}>Keep photo</button></div>:<button className="text-button" disabled={busy} onClick={()=>setConfirmDelete(true)}>Remove this photo</button>}{error&&<p role="alert" className="storage-alert">{error}</p>}</>}</DialogContent></Dialog></section>
}
