"use client";
import Image from 'next/image';
import {useState} from 'react';
import {ArrowRight,Award,Brain,Check,Clock,Footprints,Heart,Leaf,Plus,Sparkles,Users,Wallet} from 'lucide-react';
import {byId} from '@/lib/ideas';
import {receipt,type State} from '@/lib/journey';
import {dashboardActivity,durationLabel,previousReturns,returnCurrencies,returnPeriods,type ReturnPeriod} from '@/lib/dashboard';
import {collectionMonths,monthCollection,winMilestones,topWorthwhileMoments,recentWinMonths} from '@/lib/wins';
import {formatMoney} from '@/lib/regions';

type WinsProps={state:State;now:number;period:string;currency:string};

export function WinsSummary({state,now,period,currency,onPeriod,onCurrency,onAddWin,onWorkings}:WinsProps&{onPeriod:(p:ReturnPeriod)=>void;onCurrency:(c:string)=>void;onAddWin:()=>void;onWorkings:()=>void}){
 const date=new Date(now),report=receipt(state.entries,period,currency,date),activity=dashboardActivity(state,date),currencies=returnCurrencies(state,date);
 const moving=report.rows.reduce((n,e)=>n+(e.minutes||0),0),combined=report.rows.reduce((n,e)=>n+(e.timeCombined||0),0);
 const previous=previousReturns(state.entries,period as ReturnPeriod,currency,date);
 const metrics=[{label:'Movement reported',value:durationLabel(moving),note:'From your confirmed activities',Icon:Footprints,key:'movement'},
   {label:'Money kept',value:formatMoney(report.money,currency,state.profile.country),note:'Only the saving you confirmed',Icon:Wallet,key:'money'},
   {label:'Time combined',value:durationLabel(combined),note:'Movement alongside another task',Icon:Clock,key:'combined'},
   {label:'Worthwhile moments',value:String(report.worthwhile),note:'Things you said were worth it',Icon:Heart,key:'worthwhile'}];
 return <div className="wins-summary">
   <section className="wins-hero" aria-label="Your Wins overview"><div className="wins-hero-copy"><span className="eyebrow">MY WINS · CONFIRMED BY YOU</span><h1>More life.<br/>In little moments.</h1><p>{report.rows.length?`${report.rows.length} confirmed ${report.rows.length===1?'moment':'moments'} ${period==='All time'?'so far':period.toLowerCase()}. Here’s what they gave back to you.`:'A conversation, an errand, a useful pause. Confirm what happened after a move, and your returns will appear here.'}</p><button className="primary" onClick={onAddWin}><Plus size={18}/>Add a win</button></div>
     <div className="wins-week-card"><span className="eyebrow">YOUR WEEK, AT YOUR PACE</span><div><Leaf size={27}/><strong>{activity.activeDays}</strong><span>{activity.activeDays===1?'day':'days'} with a<br/>confirmed moment</span></div><div className="activity-days" aria-label="Confirmed activity this week">{activity.days.map(d=><div key={d.date} className={(d.today?'is-today ':'')+(d.future?'is-future':'')} aria-label={`${d.label}: ${d.count} confirmed moments${d.today?', today':''}`}><span className={d.count?'day-has-moment':''}>{d.count?<Check size={17}/>:<span className="day-dot"/>}</span><small>{d.label}</small></div>)}</div><p>Each check is a moment you recorded.</p></div>
   </section>
   <section className="glass-panel wins-returns-panel" aria-labelledby="wins-returns-heading"><div className="wins-section-heading"><div><span className="eyebrow">WHAT CAME BACK</span><h2 id="wins-returns-heading">Your real returns.</h2></div><div className="wins-report-controls"><label><span className="sr-only">Wins period</span><select value={period} onChange={e=>onPeriod(e.target.value as ReturnPeriod)}>{returnPeriods.map(p=><option key={p}>{p}</option>)}</select></label><label><span className="sr-only">Money totals in</span><select value={currency} onChange={e=>onCurrency(e.target.value)}>{[...new Set([currency,...currencies])].map(c=><option key={c}>{c}</option>)}</select></label></div></div>
     <div className="wins-return-strip">{metrics.map(({label,value,note,Icon,key})=><div key={key} className={'wins-return wins-return-'+key}><span className="wins-return-icon"><Icon size={25}/></span><strong>{value}</strong><span>{label}</span><small>{note}</small>{key==='money'&&previous&&<p className="wins-return-comparison">{previous.label}: {formatMoney(previous.money,currency,state.profile.country)} confirmed</p>}{key==='combined'&&moving>0&&<div className="wins-return-evidence"><span className="wins-evidence-bar"><span style={{width:Math.min(100,combined/moving*100)+'%'}}/></span><small>{combined} of {moving} moving minutes combined</small></div>}{key==='worthwhile'&&report.rows.length>0&&<div className="wins-return-evidence"><span className="wins-evidence-bar"><span style={{width:report.worthwhile/report.rows.length*100+'%'}}/></span><small>{report.worthwhile} of {report.rows.length} confirmed moments</small></div>}</div>)}</div>
     <div className="wins-returns-footnote"><p>Money stays in {currency}; currencies are kept separate. Movement and moments include all currencies. Time combined is part of moving time.</p><button className="text-button" onClick={onWorkings}>How this is worked out</button></div>
   </section>
 </div>;
}

export function WinsDetails({state,now,period,currency,day,onDay,onMoment,onPins,onBrowse}:WinsProps&{day:string|null;onDay:(day:string|null)=>void;onMoment:(id:string)=>void;onPins:()=>void;onBrowse:()=>void}){
 const date=new Date(now),months=collectionMonths(state.entries,date),[selectedMonth,setSelectedMonth]=useState<string|null>(null);
 const month=selectedMonth&&months.includes(selectedMonth)?selectedMonth:months[0],collection=monthCollection(state.entries,month,date);
 const milestones=winMilestones(state.entries,date),report=receipt(state.entries,period,currency,date),top=topWorthwhileMoments(report.rows,date),history=recentWinMonths(state.entries,date),peak=Math.max(1,...history.map(m=>m.count)),activity=dashboardActivity(state,date);
 const otherReturns=[{label:'Time outside',value:durationLabel(report.outside),Icon:Leaf},{label:'Time connecting',value:durationLabel(report.connecting),Icon:Users},{label:'Tasks completed',value:String(report.rows.filter(e=>e.gave?.includes('task_completed')).length),Icon:Check}];
 return <div className="wins-details">
   <div className="wins-detail-grid">
     <section className="glass-panel wins-collection" aria-labelledby="wins-collection-heading"><div className="wins-section-heading"><h2 id="wins-collection-heading">Your month in moments</h2><label className="widget-select"><span className="sr-only">Collection month</span><select value={month} onChange={e=>setSelectedMonth(e.target.value)}>{months.map(m=><option key={m} value={m}>{new Date(m+'-01T12:00:00').toLocaleDateString(undefined,{month:'short',year:'numeric'})}</option>)}</select></label></div><p>{collection.total?`${collection.total} confirmed ${collection.total===1?'moment':'moments'} across ${collection.activeDays} ${collection.activeDays===1?'day':'days'}.`:'A place for the moments you choose to record.'} Tap a marked day to see its moments.</p><div className="wins-calendar" aria-label={collection.label}>{['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map(w=><span className="wins-calendar-weekday" key={w}>{w}</span>)}{Array.from({length:collection.offset},(_,i)=><span key={'blank'+i} aria-hidden="true"/>)}{collection.days.map(d=><button key={d.date} disabled={!d.count} aria-label={`${d.number} ${collection.label}: ${d.count} confirmed ${d.count===1?'moment':'moments'}${d.today?', today':''}`} aria-pressed={day===d.date} className={(d.count?'calendar-has-moment ':'')+(d.today?'calendar-today ':'')+(d.future?'calendar-future':'')} onClick={()=>onDay(day===d.date?null:d.date)}><span>{d.number}</span>{d.count>0&&<Check size={11}/>}</button>)}</div>{day&&<button className="text-button" onClick={()=>onDay(null)}>Show moments from every day</button>}</section>
     <section className="glass-panel wins-milestones" aria-labelledby="wins-milestones-heading"><div className="wins-section-heading"><h2 id="wins-milestones-heading">Your milestones</h2><Award size={22}/></div><p>Small things you’ve actually recorded. Kept across all your confirmed moves.</p><div className="wins-milestone-grid">{milestones.map(m=>{const Icon=m.key==='first'?Footprints:m.key==='combined'?Clock:m.key==='connection'?Users:Wallet;return <div key={m.key} className={m.earnedAt?'milestone-earned':'milestone-not-yet'}><span className={'milestone-medal milestone-'+m.key}><Icon size={27}/>{m.earnedAt&&<span><Check size={11}/></span>}</span><strong>{m.title}</strong><span>{m.description}</span><small>{m.earnedAt?new Date(m.earnedAt).toLocaleDateString(undefined,{day:'numeric',month:'short',year:'numeric'}):'Not recorded yet'}</small></div>})}</div></section>
     <section className="glass-panel wins-everyday" aria-labelledby="wins-everyday-heading"><div className="wins-section-heading"><h2 id="wins-everyday-heading">Made room for more.</h2><Sparkles size={22}/></div><div className="wins-other-returns">{otherReturns.map(({label,value,Icon})=><div key={label}><Icon size={21}/><strong>{value}</strong><span>{label}</span></div>)}</div><p className="wins-small-note">{period} · Outside and connecting time can overlap.</p><div className="wins-history-chart" aria-label="Confirmed moments in the last five calendar months">{history.map(m=><div key={m.key} className={m.current?'chart-current':''}><span>{m.count}</span><div className="wins-month-bar"><span style={{height:m.count/peak*100+'%'}}/></div><small>{m.label}</small></div>)}</div><p className="wins-small-note">Confirmed moments by month. The current month includes today so far.</p></section>
     <section className="glass-panel wins-top-moments" aria-labelledby="top-moments-heading"><div className="wins-section-heading"><h2 id="top-moments-heading">Your top moments</h2><Heart size={22}/></div><p>{period} · Sorted by how often you said an idea was worthwhile.</p>{top.length?<ol>{top.map((m,index)=><li key={m.ideaId}><button onClick={()=>onMoment(m.entryId)}><span className="top-moment-rank">{index+1}</span><span className="top-moment-copy"><strong>{byId(m.ideaId,state.generated)?.title||'Your confirmed move'}</strong><small>{m.worthwhile} worthwhile {m.worthwhile===1?'try':'tries'} · {durationLabel(m.minutes)} reported</small><small>{Object.entries(m.money).map(([code,cents])=>formatMoney(cents,code,state.profile.country)).join(' · ')} kept</small></span><ArrowRight size={17}/></button></li>)}</ol>:<div className="wins-top-empty"><Heart size={25}/><p>Your worthwhile moments will find a home here after you confirm them.</p></div>}</section>
   </div>
   <div className="wins-bottom-grid"><section className="glass-panel wins-learning" aria-labelledby="wins-learning-heading"><div className="wins-section-heading"><h2 id="wins-learning-heading"><Brain size={22}/>What Enough has learned</h2></div><div className="wins-learning-body"><div><strong>{activity.confirmed?<>{activity.worthwhile}<small>/{activity.confirmed}</small></>:<Brain size={36}/>}</strong><span>{activity.confirmed?<>confirmed moves<br/>felt worthwhile</>:'No feedback yet'}</span></div><p>{activity.confirmed?'Your own feedback helps refine later ideas. You can change your PINS whenever life changes.':'Your PINS guide the starting ideas. Tell us what an experience gave you, and ENOUGH can learn from your feedback.'}</p></div><button className="widget-link" onClick={onPins}>Review My Pins<ArrowRight size={16}/></button></section><section className="wins-next"><Image src="/images/welcome-coast.webp" alt="" fill sizes="(max-width: 760px) 90vw, 600px"/><div><span className="eyebrow">A LITTLE POSSIBILITY</span><h2>More life, when it fits.</h2><p>A small idea inside something you’re already doing.</p><button className="primary" onClick={onBrowse}>Find your next move<ArrowRight size={18}/></button></div></section></div>
 </div>;
}
