import {z} from 'zod';
import {currencySchema,countrySchema,costSchema} from './regions.ts';
import {movementWindowSchema,movementEvidenceSchema,movementSettingsSchema} from './movement.ts';
import {catalogue} from './ideas.ts';
import {ideaSchema,valueTypes} from './idea-validation.ts';
import {completeProfile,type State} from './journey.ts';
const short=z.string().max(500),list=z.array(short).max(100);
const support=z.object({goalType:z.enum(['open','smart']),goal:short,target:short,reason:short,deadline:short,confidence:short,when:short,cue:short,place:short,placeType:short,barriers:list,fallback:short,prep:list,commitment:short,buddy:short,qrMeet:z.boolean().optional(),reward:short,reminder:z.enum(['none','in-app','calendar']),remindAt:short,reminderDismissed:z.boolean().optional(),updatedAt:short}).strict();
const iso=z.string().datetime({offset:true});const currency=currencySchema;
const entry=z.object({id:z.string().min(1).max(100),ideaId:z.number().int().min(0).max(2147483647),status:z.enum(['accepted','completed','not-today']),acceptedAt:iso,completedAt:iso.optional(),minutes:z.number().int().min(0).max(240).optional(),outside:z.boolean().optional(),connecting:z.boolean().optional(),worthwhile:z.boolean().optional(),moneyCents:z.number().int().min(0).max(100000).optional(),currency,predicted:z.array(valueTypes).max(7).optional(),gave:z.array(valueTypes).max(7).optional(),timeCombined:z.number().int().min(0).max(240).optional(),movementWindow:movementWindowSchema.optional(),movementEvidence:movementEvidenceSchema.optional(),additionalMovement:z.enum(['more','same','less','unsure']).optional(),support:support.optional(),companions:z.array(z.object({id:z.string().min(1).max(100),name:z.string().trim().min(1).max(60),source:z.enum(['qr','manual']),metAt:iso}).strict()).max(10).optional()}).strict().refine(e=>e.status!=='completed'||(e.completedAt!==undefined&&e.minutes!==undefined&&e.moneyCents!==undefined&&e.outside!==undefined&&e.connecting!==undefined&&e.worthwhile!==undefined),'Completed outcomes need confirmed fields').refine(e=>e.timeCombined===undefined||e.minutes===undefined||e.timeCombined<=e.minutes,'Combined time cannot exceed reported time').refine(e=>!e.movementEvidence||(e.movementWindow?.start===e.movementEvidence.start&&e.movementWindow?.end===e.movementEvidence.end),'Movement evidence must match the activity window');
export const stateSchema=z.object({version:z.literal(1),movementSettings:movementSettingsSchema.optional(),costs:z.array(costSchema).max(200).optional(),profile:z.object({country:countrySchema.optional(),name:z.string().max(40),preferences:list,interests:list,needs:list,strengths:list,activity:short,rhythms:list,window:short,currency,visual:list,complete:z.boolean()}).strict(),saved:z.array(z.number().int().min(0).max(2147483647)).max(200),entries:z.array(entry).max(2000),generated:z.array(ideaSchema).max(100).optional(),passes:z.array(z.object({ideaId:z.number().int().min(0),at:iso}).strict()).max(200).optional(),tuning:z.object({extraMinutes:z.number().int().min(0).max(30),travel:z.enum(['walk','drive','transit','varies']),hidden:z.array(z.number().int().min(0)).max(200)}).strict().optional(),demo:z.boolean(),today:z.object({date:short,context:short}).strict()}).strict().refine(s=>new Set(s.entries.map(e=>e.id)).size===s.entries.length,'Duplicate move IDs').refine(s=>{const ids=new Set([...catalogue.map(i=>i.id),...(s.generated||[]).map(i=>i.id)]);return (s.costs||[]).every(c=>ids.has(c.ideaId))&&s.saved.every(id=>ids.has(id))&&s.entries.every(e=>ids.has(e.ideaId));},'Unknown idea reference').refine(s=>new Set((s.generated||[]).map(i=>i.id)).size===(s.generated||[]).length,'Duplicate generated idea IDs').refine(s=>new Set((s.costs||[]).map(c=>`${c.ideaId}:${c.currency}`)).size===(s.costs||[]).length,'Duplicate cost assumptions');
export function validateState(input:unknown):State{const parsed=stateSchema.parse(input);return {...parsed,profile:{...parsed.profile,complete:completeProfile(parsed.profile)}};}
export const writeSchema=z.object({revision:z.number().int().min(0),state:stateSchema}).strict();
