"use client";
import {useEffect,useRef,useState,type Dispatch,type SetStateAction} from 'react';
import {emptyState,type State} from '@/lib/journey';
type Account={user:{email:string;name:string}|null;state:State|null;revision:number;signIn:string;signOut?:string};
export function useCloudAccount(state:State,setState:Dispatch<SetStateAction<State>>,ready:boolean){
 const [account,setAccount]=useState<Account|null>(null),[cloud,setCloud]=useState(false),[status,setStatus]=useState('checking'),[error,setError]=useState('');
 const revision=useRef(0),lastSaved=useRef(''),pending=useRef<State|null>(null),busy=useRef(false),blocked=useRef(false),current=useRef(state);current.current=state;
 const request=async()=>{const res=await fetch('/api/account',{cache:'no-store'});const data=await res.json() as Account & {error?:string;revision:number};if(!res.ok)throw Error(data.error||'Could not open your account.');return data as Account};
 const load=async()=>{try{const a=await request();setAccount(a);revision.current=a.revision;if(a.state){lastSaved.current=JSON.stringify(a.state);setCloud(true);setState(a.state);setStatus('saved')}else{setCloud(false);setStatus('local')}setError('');blocked.current=false;}catch(e){setStatus('unavailable');setError(e instanceof Error?e.message:'Your account is unavailable.')}};
 useEffect(()=>{if(ready)void load()},[ready]);
 const pump=async()=>{if(busy.current||blocked.current||!pending.current)return;busy.current=true;setStatus('saving');while(pending.current&&!blocked.current){const snapshot=pending.current;pending.current=null;try{const res=await fetch('/api/account',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({revision:revision.current,state:{...snapshot,demo:false}})});const result=await res.json() as {error?:string;revision:number};if(!res.ok){pending.current=current.current;blocked.current=true;setStatus(res.status===409?'conflict':'error');throw Error(result.error||'Could not save your account.')}revision.current=result.revision;lastSaved.current=JSON.stringify(snapshot);setError('');setStatus('saved');}catch(e){setError(e instanceof Error?e.message:'Your changes could not be saved.');if(!blocked.current){pending.current=current.current;blocked.current=true;setStatus('error')}break}}busy.current=false;};
 useEffect(()=>{if(!cloud||!ready||JSON.stringify(state)===lastSaved.current)return;pending.current=state;setStatus(s=>s==='conflict'?'conflict':'waiting');const timer=setTimeout(()=>void pump(),600);return()=>clearTimeout(timer)},[state,cloud,ready]);
 const attach=async(importLocal:boolean)=>{if(!account?.user){setError('Sign in to ENOUGH to keep your ENOUGH profile.');return false;}setStatus('saving');setError('');try{const fresh=await request();if(fresh.state){setAccount(fresh);setError('This account already has a cloud profile. Open it instead of replacing it.');setStatus('conflict');return false;}const snapshot=importLocal?{...current.current,demo:false}:emptyState();const res=await fetch('/api/account',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({revision:0,state:snapshot})});const data=await res.json() as Account & {error?:string;revision:number};if(!res.ok)throw Error(data.error||'Could not create your ENOUGH profile.');revision.current=data.revision;lastSaved.current=JSON.stringify(snapshot);blocked.current=false;pending.current=null;setState(snapshot);setCloud(true);setAccount({...fresh,state:snapshot,revision:data.revision});setStatus('saved');return true;}catch(e){setStatus('error');setError(e instanceof Error?e.message:'Could not create your profile.');return false;}};
 const retry=()=>{if(!cloud)return void load();if(status==='conflict')return;blocked.current=false;pending.current=current.current;void pump()};
 const download=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(current.current,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='enough-profile-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
 const remove=async()=>{if(busy.current||pending.current){setError('Wait for your changes to finish saving before deleting.');return false;}try{const res=await fetch('/api/account',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({revision:revision.current,confirmation:'DELETE ENOUGH DATA'})});const d=await res.json() as {error?:string};if(!res.ok)throw Error(d.error||'Could not delete your data.');blocked.current=true;pending.current=null;revision.current=0;lastSaved.current='';setCloud(false);setState(emptyState());setAccount(a=>a?{...a,state:null,revision:0}:a);setStatus('local');setError('');return true;}catch(e){setError(e instanceof Error?e.message:'Could not delete your data.');return false;}};
 return {account,cloud,status,error,attach,retry,load,download,remove,synced:cloud&&JSON.stringify(state)===lastSaved.current};
}
